apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: appwrite
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306