apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
  namespace: appwrite
  labels:
    app: maildev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
        - name: maildev
          image: appwrite/mailcatcher:1.0.0
          envFrom:
            - configMapRef:
                name: maildev-configmap