apiVersion: v1
kind: Service
metadata:
  name: appwrite-assistant # ideally appwrite-assistant-service, but source code is currently hard-codeed
  namespace: appwrite
spec:
  type: ClusterIP
  selector:
    app: appwrite-assistant
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003