apiVersion: v1
kind: Service
metadata:
  name: appwrite-api-service
  namespace: appwrite
spec:
  type: ClusterIP
  selector:
    app: appwrite-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80