apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: appwrite
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
        - name: redis
          image: redis:7.0.4-alpine
          # command: ["redis-server"]
          # args: ["--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru", "--maxmemory-samples", "5"]
          volumeMounts:
            - name: redis-volume
              mountPath: /data
          envFrom:
            - configMapRef:
                name: redis-configmap