apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
  namespace: appwrite
spec:
  type: ClusterIP
  selector:
    app: redis-commander
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081