apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: appwrite
  labels:
    app: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
        - name: redis-commander
          image: rediscommander/redis-commander:latest
          envFrom:
            - configMapRef:
                name: redis-commander-configmap