apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: appwrite
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          envFrom:
            - configMapRef:
                name: adminer-configmap